#!/bin/bash
# This hook is run after this virtualenv is activated.

export PYTHONPATH=/home/kivill/competence
export LOG_PATH=/home/kivill/competence/logs
export LOG_LEVEL=INFO
export TZ=UTC
export ENV=production

# App variables
export APP_HOST=127.0.0.1
export APP_PORT=5000
export SERVICE_NAME=competence
export APP_URL=https://datakrat.ru
export LOCALE=ru

# Database connect parameters
export DB_DRIVER=pgsql
export DB_NAME=competence
export DB_HOST=127.0.0.1
export DB_PORT=5432
export DB_USER=admin
export DB_PASSWORD=2665640

# Flask variables
export FLASK_APP=competence
export FLASK_ENV=development
export JWT_SECRET=cAtwa1kkEy